version: "3"

services:
  postgres:
    image: postgres:12.4
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application
